import type { Metadata } from "next";
import { Caudex, Inter } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'
import "./globals.css";
import Footer from "./components/layout/Footer/page";

const caudex = Caudex({
  subsets: ['latin'],
  weight: "400",
  display: 'swap',
  variable: '--font-caudex',
})

const cormorant_garamond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: "400",
  display: 'swap',
  variable: '--font-cormorant_garamond',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Ten Ten Tea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={caudex.variable + ' ' + cormorant_garamond.variable}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
